export const common = {
    type: 'Тип',
    chapter: 'Раздел',
    label: {
        number: 'Номер',
        blockTitle: 'Тайтл',
        blockInfo: 'Инфо',
        title: 'Тайтл',
        id: 'ID',
        slug: 'Slug',
        name: 'Name',
        price: 'Цена',
        description: 'Описание',
        notification: 'Уведомление',
        preview: 'Превью',
        previewActive: 'Превью активного блока',
        selectImage: 'Изображение',
    },
    term: {
        fullImage: 'Полноразмерное изображение',
        childImage: 'Изображение связанного блока',
        visibilityChangedSuccessfully: 'Видимость изменена успешно',
        duplicatedSuccessfully: 'Дублировано успешно',
        notifications: {
            blockInfoUpdated: 'Сохранено',
        },
    },
    button: {
        save: 'Сохранить',
        confirm: 'Подтвердить',
        cancel: 'Отмена',
        ok: 'Да',
    },
    notifications: {
        updated: 'Данные обновлены успешно',
    },
    blockSettings: {
        showHiddenFields: 'Показать информационные поля',
        showAllConfigurations: 'Отобразить дочерние блоки',
    },
    editBlockInfo: {
        title: 'Инфо блока',
    },
    menu: {
        dimensions: 'Размеры',
        edges: 'Кромки',
        palette: 'Палитра',
        sinks: 'Мойки',
        addons: 'Дополнения',
        result: 'Результат',
        settings: 'Настройки',
    },
    designations: {
        title: 'Обозначения',
        frontChamfer: 'Лицо с фаской',
        roundingChamfer: 'Подгиб с фаской',
        frontWithoutChamfer: 'Лицо без фаски',
        sideSkirting: 'Плинтус приставной',
        integratedSkirting: 'Плинтус интегрированный',
    },
}
