<?php

return [
    'name' => 'Производитель камня (Бренд)',
    'slug' => 'stone-category',
    'children' => [
        'N' => 'N',
        'N100' => 'N100',
        'N200' => 'N200',
        'PSD' => 'PSD',
        'A' => 'A',
        'EJMС' => 'EJMС',
        'Solo' => 'Solo',
        'Duo' => 'Duo',
        'Trio' => 'Trio',
        'Concrete' => 'Concrete',
        'Galleria' => 'Galleria',
        'Cancade' => 'Cancade',
        'Stratum' => 'Stratum',
        'Bellasimo' => 'Bellasimo',
        'Solid' => 'Solid',
        'Sanded' => 'Sanded',
        'Aspen' => 'Aspen',
        'Metallic' => 'Metallic',
        'Pebble' => 'Pebble',
        'Quarry' => 'Quarry',
        'Mosaic' => 'Mosaic',
        'Tempest' => 'Tempest',
        'Supreme' => 'Supreme',
        'Sand' => 'Sand',
        'Pearl' => 'Pearl',
        'Granite' => 'Granite',
        'Volcanics' => 'Volcanics',
        'Lucia' => 'Lucia',
        'Marmo' => 'Marmo',
        'Calacatta' => 'Calacatta',
        'Luna' => 'Luna',
    ]

];